# Generated by Django 4.1.6 on 2023-02-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='type_of_post',
            new_name='type_post',
        ),
    ]
